name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FIREBUILD_ACTION_CI: true

jobs:
  build:
    # Run npm build and check that the dist/ folder is up to date.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          git diff --exit-code

  test_firebuild:
    # Test that firebuild is installed and configured correctly.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run firebuild-action
        id: firebuild
        uses: ./
        with:
          max-size: 0.01
          key: parent
      - name: Test firebuild 1/2
        run: |
          [[ ${{ steps.firebuild.outputs.test-cache-hit }} = true ]] || [[ ${{ steps.firebuild.outputs.test-cache-hit }} = false ]]
          which firebuild
          firebuild --version
          firebuild -s
          # Example program
          echo "int x = $RANDOM;" > test.c
          firebuild gcc test.c -c -o test.o
      - name: Re-compile test program
        run: |
          firebuild gcc test.c -c -o test.o
          firebuild gcc test.c -c -o test.o
      - name: Test firebuild 2/2
        run: |
          firebuild -s
          # Only one hit is expected due to https://github.com/firebuild/firebuild/issues/1085
          firebuild -s | grep -E 'Hits:.+1.+/'
        if: ${{ !matrix.xfail }}

  test_cache_hit:
    # Test that loading from the cache works.
    needs: [test_firebuild]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run firebuild action
        uses: ./
        id: output
        with:
          key: parent
      - name: Test output true
        run: |
          [[ ${{ steps.output.outputs.test-cache-hit }} = true ]]

  test_cache_miss:
    # Test that cache misses do not break anything.
    needs: [test_firebuild]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "RAND=$RANDOM" >> $GITHUB_ENV
      - name: Run firebuild action
        uses: ./
        id: output
        with:
          key: random-key-${{ env.RAND }}
      - name: Test output false
        run: |
          [[ ${{ steps.output.outputs.test-cache-hit }} = false ]]

  test_restore_keys:
    # Test the "restore-keys" option.
    needs: [test_firebuild]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "RAND=$RANDOM" >> $GITHUB_ENV
      - name: Run firebuild action
        uses: ./
        id: restore-keys
        with:
          key: child-${{ env.RAND }}
          restore-keys: |
            parent
      - name: Test restore-keys
        run: |
          [[ ${{ steps.restore-keys.outputs.test-cache-hit }} = true ]]

  test_docker:
    # Test that it works in a Docker container without sudo.
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt update
      - name: Run firebuild-action
        uses: ./

  test_option_save:
    # Test that the 'save' option is available.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        save: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Run firebuild-action
        uses: ./
        with:
          save: ${{ matrix.save }}
